version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: users-mongo-final
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-user-api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=users_db
      - MONGO_COLLECTION_NAME=users

volumes:
  mongo_data:
